package packet;

import java.util.HashMap;

public enum STCHeader {
	LOGIN(0),
	REGISTER(1),
	MOVE_CHARACTER(2),
	TURN_CHARACTER(3),
	CREATE_CHARACTER(4),
	REMOVE_CHARACTER(5),
	REFRESH_CHARACTER(6),
	JUMP_CHARACTER(7),
	ANIMATION_CHARACTER(8),
	MOTION_CHARACTER(9),
	UPDATE_CHARACTER(10),
	DAMAGE_CHARACTER(11),
	LOAD_DROP_ITEM(12),
	LOAD_DROP_GOLD(13),
	REMOVE_DROP_ITEM(14),
	REMOVE_DROP_GOLD(15),
	NOTIFY(16),
	MOVE_MAP(17),
	CHAT_NORMAL(18),
	CHAT_WHISPER(19),
	CHAT_PARTY(20),
	CHAT_GUILD(21),
	CHAT_ALL(22),
	CHAT_BALLOON_END(23),
	PLAY_MUSIC(24),

	OPEN_REGISTER_WINDOW(100),
	UPDATE_STATUS(101),
	SET_ITEM(102),
	UPDATE_ITEM(103),
	SET_SKILL(104),
	UPDATE_SKILL(105),
	REQUEST_TRADE(106),
	OPEN_TRADE_WINDOW(107),
	LOAD_TRADE_ITEM(108),
	DROP_TRADE_ITEM(109),
	CHANGE_TRADE_GOLD(110),
	FINISH_TRADE(111),
	CANCEL_TRADE(112),
	OPEN_MESSAGE_WINDOW(113),
	CLOSE_MESSAGE_WINDOW(114),
	SET_SHOP_ITEM(115),
	SET_PARTY(116),
	INVITE_PARTY(117),
	SET_PARTY_MEMBER(118),
	REMOVE_PARTY_MEMBER(119),
	CREATE_GUILD(120),
	SET_GUILD(121),
	INVITE_GUILD(122),
	SET_GUILD_MEMBER(123),
	REMOVE_GUILD_MEMBER(124),
	OPEN_SHOP_WINDOW(125),

	SET_SLOT(200),
	SET_COOL_TIME(201);

	private static HashMap<Integer, STCHeader> caches;

	private final int mValue;

	STCHeader(final int value) {
		mValue = value;
	}

	public static STCHeader fromInt(final int value) {
		if (caches == null) {
			caches = new HashMap<>();
			for (STCHeader cache : values()) {
				caches.put(cache.mValue, cache);
			}
		}
		return caches.get(value);
	}

	public int getValue() {
		return mValue;
	}
}